import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { OverlayProvider } from "@/components/overlay";
import CustomCursor from "@/components/cursor"
import Chat from "@/components/chat-ai";

export const metadata: Metadata = {
  title: "LynxAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua" id="html">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <Providers>
        <body className={`antialiased`}>
          <OverlayProvider>
            <CustomCursor />
            <Header />
            <main>{children}</main>
            <Chat />

            <Footer />
          </OverlayProvider>
        </body>
      </Providers>
    </html>
  );
}
