import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { OverlayProvider } from "@/components/overlay";

export const metadata: Metadata = {
  title: "LynxAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <Providers>
        <body className={`antialiased`}>
          <OverlayProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </OverlayProvider>
        </body>
      </Providers>
    </html>
  );
}
