import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Header from '@/components/header'
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "LynxAI",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <Providers>
        <body className={`antialiased`}>
          <Header />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
